### ISSUE TITLE
I want to use heros implement inter-procedural analysis,but I didn't how to use it.

### ISSUE THREAD

**Issue by ZhengqiaoLi** [Sable/heros#22]
Is there some  complete engineering examples?

**Comment by ZhengqiaoLi** [comment]
I found this link http://www.bodden.de/tools/heros/ pointing to examples here https://github.com/Sable/soot/tree/master/src/soot/jimple/toolkits/ide/exampleproblems.

But I didn't use soot to debug the example code.

**Comment by ericbodden** [comment]
Please see here: https://github.com/Sable/heros/wiki/Example%3A-Using-Heros-with-Soot
