### ISSUE TITLE
flowfunc/Transfer uses == instead of equals(..)

### ISSUE THREAD

**Issue by Waldo1637** [Sable/heros#27]
commit 19cb6fbd0be3eed029a9b4ca706885ee23d7e6e0 fixed the same issue in flowfunc/Kill but use of == remains in the Transfer class.

The same usage also exists in flowfunc/Gen but shouldn't cause any issues there if IFDSTabulationProblem#zeroValue() is always used to obtain the unique instance of zero.

**Comment by ericbodden** [comment]
Thanks! Would you like to provide a pull request for this? I think then we should fix it in Gen, too. (it should not hurt doing so)

**Comment by Waldo1637** [comment]
I performed the replacement of == with equals(..) in both Transfer and Gen and created a pull request.
