### ISSUE TITLE
How to use FieldSensitiveIFDSSolver?

### ISSUE THREAD

**Issue by coder-chenzhi** [Sable/heros#38]
I found existing [examples](https://github.com/Sable/heros/wiki/Example%3A-Using-Heros-with-Soot) of using the Heros' IFDS solver with Soot. However, it was written using Soot v. 3.1.0 and Heros v. 1.0.1. And  no examples use the FieldSensitiveIFDSSolver.

**Comment by ericbodden** [comment]
Hi there. I believe that FieldSensitiveIFDSSolver is actually outdated. I'd encourage you to look at our IDEal implementation here instead: https://github.com/CROSSINGTUD/WPDS
It is described in our recent POPL paper: http://www.bodden.de/pubs/sab19context.pdf
IDEal has many advantages over Heros, one being its treatment of field sensitivity.

**Comment by ericbodden** [comment]
Did this help? Can we close the issue?

**Comment by coder-chenzhi** [comment]
Thanks for your information.
