### ISSUE TITLE
How to run backwards IFDS?

### ISSUE THREAD

**Issue by coder-chenzhi** [Sable/heros#39]
I found existing [examples](https://github.com/Sable/heros/wiki/Example%3A-Using-Heros-with-Soot) of using the Heros' IFDS solver with Soot.  Following is the example driver code. However, it performs IFDSReachingDefinitions, which is forward analysis. From my understanding, the IFDSLiveVariable should be backward analysis. What should I do if I want to run the IFDSLiveVariable? For example, should I change the type of ICFG to BackwardsInterproceduralCFG? 
```
// Subclass of SceneTransformer to run Heros IFDS solver in Soot's "wjtp" pack
public class IFDSDataFlowTransformer extends SceneTransformer {
    @Override
    protected void internalTransform(String phaseName, Map<String, String> options) {
        JimpleBasedInterproceduralCFG icfg= new JimpleBasedInterproceduralCFG();
        IFDSTabulationProblem<Unit, Pair<Value, 
                Set<DefinitionStmt>>, SootMethod, 
                InterproceduralCFG<Unit, SootMethod>> problem = new IFDSReachingDefinitions(icfg);

        IFDSSolver<Unit, Pair<Value, Set<DefinitionStmt>>, 
                SootMethod, InterproceduralCFG<Unit, SootMethod>> solver = 
                    new IFDSSolver<Unit, Pair<Value, Set<DefinitionStmt>>, SootMethod, 
                                   InterproceduralCFG<Unit, SootMethod>>(problem);

        System.out.println("Starting solver");
        solver.solve();
        System.out.println("Done");
    }
}
```

Thanks!

**Comment by ericbodden** [comment]
Yes that is correct, you should be using BackwardsInterproceduralCFG. Please reopen if this does not answer your question.
